### ISSUE TITLE
ios13 beta Produces strange orientations

### ISSUE THREAD

**Issue by kallipigous** [MetalPetal/MetalPetal#90] opened 2019-06-27 17:38 UTC
I have a landscape app that uses Metal Petal and on the ios13 beta the previews in MTIImageView appear squashed. Videos recorded and images taken are the correct orientation and shape but the preview seems to squash the landscape image into a portrait frame regardless of the size of the images. Is this a known issue? 

This appears to be the same with the metal petal demo.

**Comment by YuAo** [comment] 2019-06-28 06:28
Reproduced, seems to be a problem with the layer's transform. Will investigate.

**Comment by YuAo** [comment] 2019-07-01 10:34
@kallipigous  Could you please send me a demo project or some screenshots of this issue?

**Comment by kallipigous** [comment] 2019-07-01 13:54
Sadly it does not for me. When I force it to landscape right only and compile it everything is squashed horizontally. In the live camera example it's also rotated by 90 degrees in landscape mode, but the static image rendering example just squashes it. Tilting the iphone results in the image warping as its' tilted.  This is on iOS 13 beta 2 on an iphone 7 plus. 

![IMG_0667](https://user-images.githubusercontent.com/609665/60441802-a081b700-9bcc-11e9-92e0-4d9df9d60c0d.png)

Here is how it looks on our app

![IMG_0666](https://user-images.githubusercontent.com/609665/60441847-b3948700-9bcc-11e9-81e5-f78bd22485f2.png)

**Comment by YuAo** [comment] 2019-07-02 05:55
Could you attach the demo project you modified? I cannot reproduce here. 
Tested configuration: 
Xcode 11 Beta 2, iOS 13 Beta 2, iPhone SE
MetalPetal Demo + "Device Orientation" only checked "Landscape Right"

**Comment by kallipigous** [comment] 2019-07-02 15:44
Well that's fascinating. I installed ios 13 on an old iphone SE and sure enough it works as expected. But not on an iphone 7 plus. Do you have any other devices you can test it on? We were alerted to this by people who use our app out in the field who have upgraded to ios13 and so far I have seen reports on iphone 7, iPhone Xs Max and I have seen it on an iPhone 7 plus too. Is this to do with a different generation of Graphics chip?

**Comment by kallipigous** [comment] 2019-07-02 16:42
Here's a good example of the strangeness between the two devices.

The scenekit camera example in landscape (with the camera orientation set to landscapeRight as before)

Here it is on an iphone SE

![IMG_0091](https://user-images.githubusercontent.com/609665/60530279-43a9fd80-9cad-11e9-9c1c-c1c93dd6240b.png)

Note the video is correct but the model is stretched.

on an Iphone 7 plus the same settings produce this

![IMG_0670](https://user-images.githubusercontent.com/609665/60530369-6dfbbb00-9cad-11e9-9829-322484d0cc03.png) Which is essentially what I see in my app though I apply crops and scales so it produces a different, weirder aspect ratio.

**Comment by kallipigous** [comment] 2019-07-02 17:54
Here's an interesting clue. Setting the MTIImageView resizingMode to .scale on the newer devices on ios13  seems to fix it. However that beaks it on devices on ios 12 which need .aspect to work correctly.

**Comment by kallipigous** [comment] 2019-07-02 21:02
I think I have found where the discrepancy is.

in MTIContext+rendering.m there is a line

CGSize drawableSize = CGSizeMake(renderPassDescriptor.colorAttachments[0].texture.width, renderPassDescriptor.colorAttachments[0].texture.height); 

This seems to be returning inaccurate aspect ratios of the texture.  

Logging this on the iphone 7 plus I get this as the size {2276, 405} which is an aspect ratio of about 5.6  whereas on ios 12 for the iphone XSMax I get {1280, 591} which is more or less the same aspect ratio as the device (2.16).

It's not clear to me where the renderpassdescriptor gets its texture size from but clearly apple is reporting something differently on later devices.

**Comment by YuAo** [comment] 2019-07-03 03:08
Interesting... I think it's probably a beta bug.
I do not have iPhone 7 Plus, X or X Max with iOS 13 beta at hand currently. I'll try to find one of these devices. 
BTW, beta 3 is out today. Can you check whether the issue still exists?

**Comment by kallipigous** [comment] 2019-07-03 04:20
As far as I can tell it’s still there. A newer iPad will work too. I will test that again tomorrow. Could we not get the aspect ratio directly from the view frame instead?

**Comment by YuAo** [comment] 2019-07-03 10:10
Using the view's frame directly is not a very good workaround.

1. A view's frame does not always reflect the size of its content. If a view has some `transform`, its `frame` is also transformed, which is not what we want.

2. We can use the view's `bounds` to resolve problem 1. But we'll still have some problems with the final result. Because we draw on a stretched canvas (the drawable's texture), the texture quality may degrade. For instance, drawing a 1280x720 image to a 2276x405 drawable, the on-screen texture only has 405 vertical pixels instead of 720 vertical pixels.

Here's a similar workaround you can try now, without modifying MetalPetal:

1. Set the `resizingMode` of your `MTIImageView` to `.scale`, so the image will scale to fill the image view.

2. Embed the `MTIImageView` in a container view, layout the image view inside the container to respect the image's aspect ratio. (You can use Autolayout or `AVMakeRectWithAspectRatioInsideRect`)

**Comment by kallipigous** [comment] 2019-07-03 14:27
I actually already tried this but rotating the device was skewing the pixels in a weird way on ios13 when you're using .scale. Though I'll check to make sure that I have the frame size correct. Also sadly I sometimes do anamorphic squeezes (to correct for anamorphic lenses) in the app that means the aspect ratio is often very strange and then it also get's cropped to match camera sensor sizes which might complicate things a  great deal.

I've just checked an ipad pro with ios13 and its wrong too but in a different way. it's just subtly squashed horizontally. I also had another note today from another user using an iphone 6s. My suspicion is it's anything above an iphone SE.  

Is it worth filing a radar with Apple on ios13. I'd do it but I'm not sure I understand enough about what's going on under the hood to file it.

**Comment by YuAo** [comment] 2019-07-04 11:21
Tested on an iPhone X with iOS 13 beta 2, it works as expected.

**Comment by kallipigous** [comment] 2019-07-04 14:19
I just tried it on the iPhone X ios beta 3. The static image rendering is correct, but "Working with scenekit" example shows the same problem in landscape. 

![IMG_2192](https://user-images.githubusercontent.com/609665/60673186-146dca80-9e2c-11e9-96ec-329f2b1a1b67.png)

**Comment by YuAo** [comment] 2019-07-05 09:40
Finally reproduced the issue.

Looks like a bug with `MTKView`'s `contentScaleFactor`. If the `contentScaleFactor` is less than the screen's `nativeScale` the issue occurs.

A quick fix would be subclassing `MTIImageView`, override the `updateContentScaleFactor` method and do nothing.

```
@interface MTIImageViewFix : MTIImageView
@end

@implementation MTIImageViewFix

- (void)updateContentScaleFactor {
    //do nothing
}

@end

```

Or in swift:

```
class MTIImageViewFix: MTIImageView {

    @objc func updateContentScaleFactor() {

    }

}
```

However, doing this may degrade your render performance. Because we may render the image bigger than needed.

**Comment by omarojo** [comment] 2019-07-05 09:55
Thank you for looking into this while we all prepare for iOS13.

**Comment by kallipigous** [comment] 2019-07-05 15:47
Bingo. Yes using MTIThreadSafeImageView solves it immediately. A great solution; thanks so much. I've converted the app to resize the MTIImageView according to all the aspect ratios we use but it makes me more comfortable to use .aspect in case there's a discrepancy at some point.

**Comment by YuAo** [comment] 2019-07-07 02:52
@kallipigous It requires more work to release the official pod, because`CAMetalLayer` is not available for Simulators with Xcode 10 (Apple's problem) while CocoaPods (currently version 1.7.3) can only validate libs on Simulators (CocoaPods' problem).

**Comment by kallipigous** [comment] 2019-07-07 04:50
Many, many thanks.

**Comment by YuAo** [comment] 2019-07-09 02:48
@kallipigous Pod updated.

**Comment by kallipigous** [comment] 2019-07-09 17:26
Great. many thanks.

**Comment by YuAo** [comment] 2019-08-23 07:57
It seems the problem is fixed in the latest beta. Closing this issue for now.

**Closed by YuAo** 2019-08-23 07:57 UTC
