### ISSUE TITLE
Shader complier issue with Xcode 12 on iOS 10

### ISSUE THREAD

**Issue by evan-lei** [MetalPetal/MetalPetal#210] opened 2020-10-29 13:06 UTC
Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED

Error Domain=AGXMetalA8 Code=1 "Could not resolve texture/samplers references" UserInfo={NSLocalizedDescription=Could not resolve texture/samplers references}

**Comment by YuAo** [comment] 2020-10-30 13:54
Does this happens only on iOS 10.2? I cannot reproduce this with iOS 10.3.1. Which filter are you using. Can you attach a demo project?

**Comment by evan-lei** [comment] 2020-11-02 02:49
> Does this only happen on iOS 10.2? I cannot reproduce this with iOS 10.3.1. Which filter are you using. Can you attach a demo project?
Yes，It only happens on IOS 12 devices and is a compiled version of Xcode 12. Xcode11 does not have this problem.The demo you provided also has this problem

**Comment by evan-lei** [comment] 2020-11-02 07:32
> Does this only happen on iOS 10.2? I cannot reproduce this with iOS 10.3.1. Which filter are you using. Can you attach a demo project?

使用Xcode 12.0以上版本编译会有这个问题，Xcode11编译都是ok的.

刚才发现在iOS 10.3.2 也有这个问题

在MTIContex类里，执行方法 "renderPipelineWithDescriptor"的时候, 创建MTLRenderPipelineState报错了，错误信息是"Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED"，fragmentFunction 是 “passthrough”.

我怀疑是采样器的问题，去passthrough里面，把采样改一下，不使用传入进来的，passthrough就不报错了，但是其他未改的fragment函数，依旧会报错

fragment float4 passthrough(
        VertexOut vertexIn [[ stage_in ]],
        texture2d<float, access::sample> colorTexture [[ texture(0) ]]
//        sampler colorSampler [[ sampler(0) ]]
    ) {
        return colorTexture.sample(colorSampler, vertexIn.textureCoordinate);
    }

**Comment by YuAo** [comment] 2020-11-03 04:22
@evan-lei 看起来像是编译器的BUG，把所有的shader放到一个.metal文件里好像就没问题了。

**Comment by evan-lei** [comment] 2020-11-03 06:32
> @evan-lei 看起来像是编译器的BUG，把所有的shader放到一个.metal文件里好像就没问题了。

是属于编译器的bug，Xcode12，12.0.1，12.1我都试了，目前来看都有问题，不知道苹果在后续版本的Xcode里会不会修复这个问题

**Comment by gpapoyan95** [comment] 2020-11-04 22:00
very informative :)

**Comment by YuAo** [comment] 2020-12-03 06:08
Looks like the Metal complier shipped with Xcode 12 (12.0, 12.1, 12.2) cannot generate suitable metal library for iOS 10. The issue is not observed with Xcode 11.

A temporary workaround is **merging all the shader codes to one `.metal` file**

**Comment by YuAo** [comment] 2021-07-26 06:34
This issue is resolved in Xcode 13 beta 3.

**Closed by YuAo** 2021-07-26 06:34 UTC
